# Generated by Django 2.2.6 on 2020-01-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(max_length=40)),
            ],
        ),
    ]
